spring:
  application:
    name: energytracker

  datasource:
    url: jdbc:postgresql://localhost:5432/energytracker
    username: user
    password: user
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
